language: go

go:
  - 1.2

after_success:
  - go build
  - tar cvzf "$ARTIFACT" bumper
  - git tag "$TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key: "$API_KEY"
  file: "$ARTIFACT"
  skip_cleanup: true

env:
  global:
    - ARTIFACT=bumper.tar.gz
    - secure: "P1Nq+PD79mREf0YnWI0hw/gDqYwilQ8mqLRJlbrfROBCIkQL7oE73pjfsfW8VhgCL1ZtiXhQw+JKzSt9EvnH9R8GLU3sZpO9Yzmlip42iWEQBYkGbUY9VY1TsRU5Eks714jjYLPBorZ8LjFGxS0TGJ1E5KI2kxAyHy9auiOgcMg="
