language: go

branches:
  except:
    - /^[0-9]/

go:
  - 1.3

script:
  - go build -ldflags "-X main.version $TRAVIS_BUILD_NUMBER"
  - go test -v

after_success:
  - tar cvzf "$ARTIFACT" bumper
  - git tag "$TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key: "$API_KEY"
  file: "$ARTIFACT"
  skip_cleanup: true

env:
  global:
    - ARTIFACT=/tmp/bumper.tar.gz
    - secure: "b5U+LPExdvl+LCn63BTT6ET8ge6HQVmfRqO1jNJoNS7Fhn+80+ZJCjSodxU1coqRWkDlhs3rOoO6xk8JjNfncFcoHHEUgvVnDq0T2/+T0TudkQH3uTwCm7cCSmn/TXaVRH0Gqe03mi4JYi/RmbOQCGhSyzmBjbg4oDwjMLpaxsg="
